services:
  - type: web
    name: aquasense
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn aquasense.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: aquasense.settings
      - key: SECRET_KEY
        value: django-insecure-+_ezyesvw8lwbv=gtb)y%$w8n7-p!(mp_w=69e@#9(_a#2b&=2
      - key: DEBUG
        value: False
